### ISSUE TITLE
How to build for Tomcat?

### ISSUE THREAD

**Issue by mjza** [jpenninkhof/odata-boilerplate#8]
When I try `mvn clean install` it build the `odata-0.1.0.war` file, but when I deploy it in tomcat I cannot run it. It will show this error: `FAIL - Application at context path [/odata-0.1.0] could not be started`

How ever I can run the project inside the Eclipse with MySql !

When I try to run it with tomcat server inside the eclipse it shows this error:

> SEVERE: Error during ServletContainerInitializer processing
> javax.servlet.ServletException: Failed to instantiate WebApplicationInitializer class
> 	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:160)
> 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5140)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
> 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
> 	at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
> 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
> 	at java.util.concurrent.FutureTask.run(Unknown Source)
> 	at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
> 	at java.util.concurrent.AbstractExecutorService.submit(Unknown Source)
> 	at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
> 	at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
> 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
> 	at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
> 	at java.lang.reflect.Method.invoke(Unknown Source)
> 	at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
> 	at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:474)
> Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
> 	at com.penninkhof.odata.Application.<clinit>(Application.java:18)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
> 	at java.lang.reflect.Constructor.newInstance(Unknown Source)
> 	at java.lang.Class.newInstance(Unknown Source)
> 	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:157)
> 	... 29 more
> Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
> 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
> 	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
> 	... 36 more

Any solution for building and running in Tomcat 9?

**Comment by mjza** [comment]
I solved my issue [here](https://stackoverflow.com/questions/61793790/how-to-solve-failed-to-instantiate-webapplicationinitializer-class).

@jpenninkhof  Maybe it is a good idea that you take a look and update the pom.xml or something similar!
